### ISSUE TITLE
Ember driver : Error while parsing received frame, status=NO_RX_SPACE.

### ISSUE THREAD

**Issue by vauhallan** [Koenkk/zigbee-herdsman#1000]
Hi,

Adapter: Sonoff ZBDONGLE-E
Firmware version: 7.4.0.0 build 0
Zigbee-herdsman version: 0.40.3
Link to zigbee-herdsman debug logs: no

I tried to move from EZSP to Ember driver on my configuration:
- Zigbee2mqtt inside Home assistant (HASS)
- Raspberry pi 5 8GB RAM
- Dongle Sonoff Zigbee 3.0 Dongle plus EFR32MG21 ZBDONGLE-E
- Zigbee2mqtt 1.36.1-1
- Hass core 2024.3.3
- Hass supervisor 2024.03.1

Zigbee2mqtt crash with following error message..

How to identify id failure (18934 fro example) ?

Received network/route error ROUTE_ERROR_MANY_TO_ONE_ROUTE_FAILURE for "18934".
Received network/route error ROUTE_ERROR_MANY_TO_ONE_ROUTE_FAILURE for "18934".
Received network/route error ROUTE_ERROR_MANY_TO_ONE_ROUTE_FAILURE for "38865".
Received network/route error ROUTE_ERROR_MANY_TO_ONE_ROUTE_FAILURE for "58228".
Received network/route error ROUTE_ERROR_MANY_TO_ONE_ROUTE_FAILURE for "18934".
Received network/route error ROUTE_ERROR_NON_TREE_LINK_FAILURE for "35153".
Received network/route error ROUTE_ERROR_MANY_TO_ONE_ROUTE_FAILURE for "18934".
Received network/route error ROUTE_ERROR_MANY_TO_ONE_ROUTE_FAILURE for "38865".
Error while parsing received frame, status=NO_RX_SPACE.
!!! NCP FATAL ERROR reason=HOST_FATAL_ERROR. ATTEMPTING RESET... !!!
┌──────────────┬──────────┬─────────────┐
│   (index)    │ Received │ Transmitted │
├──────────────┼──────────┼─────────────┤
│ Total frames │  11985   │    14925    │
│  Cancelled   │    0     │      0      │
│ DATA frames  │  11763   │    3362     │
│  DATA bytes  │  348286  │   146318    │
│ Retry frames │    29    │     103     │
│  ACK frames  │    98    │    11459    │
│  NAK frames  │    94    │      0      │
│ nRdy frames  │    0     │     24      │
└──────────────┴──────────┴─────────────┘
┌──────────────────┬──────────┐
│     (index)      │ Received │
├──────────────────┼──────────┤
│    CRC errors    │    1     │
│   Comm errors    │    0     │
│ Length < minimum │    0     │
│ Length > maximum │    0     │
│   Bad controls   │    0     │
│   Bad lengths    │    0     │
│ Bad ACK numbers  │    0     │
│  Out of buffers  │    1     │
│   Retry dupes    │    26    │
│ Out of sequence  │    0     │
│   ACK timeouts   │    9     │
└──────────────────┴──────────┘

**Comment by Nerivec** [comment]
The error preventing Z2M from starting is

> Error while parsing received frame, status=NO_RX_SPACE.

Which means Z2M is somehow flooded with so many messages that it can't keep up.
Networks with 200+ devices have no issues with this, so this is very strange.
What size is your network?
Do you have any device you know to be very spammy?

You will have to enable [herdsman debug](https://www.zigbee2mqtt.io/guide/usage/debug.html#zigbee-herdsman-debug-logging) to get more precise logs so we can figure out what is happening.

_Network/route errors on start is common, it's not a problem, the adapter just needs some time to catch up. PS: The number is the network address of the device in [decimal format](https://www.binaryhexconverter.com/decimal-to-hex-converter)._
