### ISSUE TITLE
IP socket as alternativ to serial port

### ISSUE THREAD

**Issue by KoljaWindeler** [Koenkk/zigbee-herdsman#101]
Hi, 
want do you think about adding a IP sockets connection in addition to the serial port?

I'm using socat to create a virtual serial socket which sort of work, but every once in a while the connection crashes. At that point my script has to shut down socat and zigbee2mqtt and start all over. 

It would be nice if zigbee-herdsman could connect directly via IP and also handle those rare reconnects. 
Kolja

**Comment by Koenkk** [comment]
This is already possible in the latest-dev, docs: https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/how_tos/how_to_connect_to_a_remote_adapter.md

**Comment by KoljaWindeler** [comment]
outstanding! thanks a lot! (sorry, didn't find it in the docs .. )

**Comment by KoljaWindeler** [comment]
hi @Koenkk any chance that you'll add a reconnect mechanism? It works now without socat and thats great, but will still require to restart once it disconnects .. not a big issue but might be a nice improvement

**Comment by Koenkk** [comment]
@hdo could you take a look at this?

**Comment by Koenkk** [comment]
@hdo could you take a look at this?

**Comment by hdo** [comment]
> @hdo could you take a look at this?

I'll take a look into this.

@KoljaWindeler Why does the disconnect happen? How can i reproduce this?
My setup is running for almost 3 weeks and i didn't encounter any disconnects.

**Comment by KoljaWindeler** [comment]
Hi, I guess this isn't due to zigbee2mqtt .. but sometimes wifi signals get yammed or the client device restarts for other reasons etc .. it's just likely that the connection won't stay stable forever, right?
Thanks for your work!

**Comment by hdo** [comment]
> Hi, I guess this isn't due to zigbee2mqtt .. but sometimes wifi signals get yammed or the client device restarts for other reasons etc .. it's just likely that the connection won't stay stable forever, right?
> Thanks for your work!

This could be a reason. Are you using ESP32 as serial tcp bridge?
