### ISSUE TITLE
Make device.lastSeen persistent across restarts

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman#106]
As mentioned in koenkk/zigbee2mqtt#2464 device.lastSeen is not persistent, it would help if it was to ensure we do not 'forget' about devices via deviceAvail.

**Comment by sjorge** [comment]
I opened #107 but I am not sure how to test this as dropping in the .ts files doens't seem to work

**Comment by Koenkk** [comment]
merged, thanks!
