### ISSUE TITLE
Silabs Zigbee EmberZNet 8.0.0.0 (and Silicon Labs Gecko SDK 5.0.0.0) announced and to be released in Q3 2024

### ISSUE THREAD

**Issue by Hedda** [Koenkk/zigbee-herdsman#1093]
@Nerivec @kirovilya heads-up; Silicon Labs is phasing out EFR32MG1x + older HW not included in new Simplicity SDK version:

EZSP protocol version incremented to EZSP v14 in Zigbee EmberZNet v8.0.0.0 + also migrated from Gecko SDK to Simplicity SDK.

Updated documentation for EmberZNet 8.0.0 and EZSP v14 looks to still be missing though -> https://github.com/SiliconLabs/simplicity_sdk/issues/11
I understand EZSPv14 and migration to Simplicity SDK (Simplicity SDK 2024.6.0) could mean breaking changes? As per comment:

* https://github.com/NabuCasa/silabs-firmware-builder/pull/74

> **_"Most `EMBER_` constants have been renamed to `SL_ZIGBEE_` and must be renamed in your manifests accordingly. This is a fairly large breaking change."_**

FYI, Silabs Zigbee EmberZNet 8.0.0.0 + Gecko SDK 5.0.0.0 + Simplicity SDK Suite 2024.6.0 been announced but not yet released:

https://www.silabs.com/developers/software-development-kit-release-notes

Silabs Zigbee EmberZNet 8.0.0.0 + Gecko SDK 5.0 (plus Simplicity SDK Suite 2024.6.0), etc. is scheduled to be released very soon:

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-8.0.0.0.pdf

https://www.silabs.com/documents/public/release-notes/gecko-platform-release-notes-5.0.0.0.pdf

https://www.silabs.com/developers/simplicity-software-development-kit

https://github.com/SiliconLabs/gecko_sdk

https://github.com/SiliconLabs/simplicity_sdk

#### New Components in release 8.0.0.0
• Inter Process Communication
Added a new component named “zigbee_ipc”.
This component adds support for interprocess communication on a Zigbee RTOS device.
• Byte utilities
Added a new utility component named “byte_utilities” outside Zigbee protocol for data store and fetch routines.
As part of that, moved the header file byte-utilities.h from protocol/zigbee/stack/include/ to util/plugin/byte_utilities.
Since this is not specific to Zigbee, the API has been renamed, from sl_zigbee_reverse_mem_copy() to sl_util_reverse_mem_copy().
• Separated a new component "Zigbee System Common (App Framework Task)" from Zigbee System Common, to better allow for apps that do not bring in the full ZCL and app framework but still use the app framework's RTOS task.
• RTOS Configurations

#### New APIs in release 8.0.0.0
• A new event initialization function sl_zigbee_af_isr_event_init is added for the events that can be activated in ISR.
Note that with this release the APIs have been renamed. For details, see the Zigbee v8.0.0 section of https://docs.silabs.com/.

#### New Application in release 8.0.0.0
• Zigbee Unified Test Harness SoC application is introduced as a new application in this release.
• Added a new ZigbeeMinimalRtos app to Zigbee offerings. This is a test application with a bare minimum RTOS based Zigbee stack. This application is non-compliant since it does not have all the necessary component and configurations of a fully functional Zigbee application.
• A new configuration for the SPI based NCP as a sleepy NCP is introduced in this release. This serves the use case of a host-SPI NCP configuration to be used as a sleepy node in the network. The host controls the sleep and wake up of the SPI NCP. See AN711: SPI Host Interfacing Guide for Zigbee for more details.

#### New Platform Support in release 8.0.0.0
•  New hardware xG26 and xG22E.
•  new platform component, Clock Manager, is integrated into all Zigbee sample applications for clock configuration.

![image](https://github.com/zigpy/zigpy/assets/6320001/24124a98-49d1-448f-9dfc-19ae5a6fb58a)

Note! EmberZNet 8.0.0.0 and Gecko Platform remove support for EFR32 Series 0/1 (e.i. EFR32MGx and EFR32MG1x) so need to use separate SDKs for Series 0 & 1 and Series 2 & 3 Starting in Q2 2024 (June 2024) as the new Gecko Platfoprm and SDK are designed specifically for our EFR32 Series 2 and upcoming Series 3 devices only.

So only EFR32MG2x and EFR32MG3x will be supported upcoming EmberZNet 8.x.x.x.x firmware as old EFR32MG1x is phased out:

"_Meanwhile, our Gecko Software Development Kit (GSDK) will continue to be available for users of our Series 0 and Series 1 devices. The Gecko SDK will continue to support all [Series 0 and 1 devices](https://www.silabs.com/developers/software-development-kit-release-notes/series-directory) with no change to the long-term support, maintenance, quality, and responsiveness provided under our software policy.The new SDK will branch from Gecko SDK and begin to offer new features that help developers take advantage of the advanced capabilities of our Series 2 and 3 products._"

## SDK Release Notes Q2/2024  (June 2024)

* New in Zigbee Zigbee EmberZNet v8.0.0.0
  * Zigbee re-architecture to support stack and framework to be fully RTOS based
  * Memory management update
  * New clock manager component integrated in Zigbee applications
  * Support Sleepy NCP use case
  *  [Zigbee Green Power (ZGP / Zigbee GP) Revision 1.1.2 ](https://csa-iot.org/newsroom/the-connectivity-standards-alliance-releases-green-power-1-1-2-for-zigbee-based-energy-harvesting-technology/)
  * Removed support for Series 0/1 (making EFR32MG1x deprecated but till supported EmberZNet v7.4.x.x with bug-fixes only)
  * [Added support for new platform xG26 (EFR32MG26)](https://news.silabs.com/2024-04-09-Silicon-Labs-xG26-Sets-New-Standard-in-Multiprotocol-Wireless-Device-Performance)
  * Alpha : Added support for Series 3  (xG3x family, e.i. EFR32MG3x series)
  * Alpha: New application for Zigbee Unified Test Harness
* New in Multiprotocol support
  * Alpha: Support for OpenWRT on host processor of multiprotocol RCP solution
  * Alpha: Support for Concurrent Zigbee and Matter over OpenThread, with DMP BLE

### New in Gecko Platform Version 5.0.0.0
* Migration to Simplicity SDK Suite
* Removed support for Series 0/1
 * Peripherals
  * New API names introduced for low-level drivers (with compatibility layer for old names)
* Services
  * Memory Manager, APIs to manage embedded dynamic memory allocations
  * Clock Manager, for clock tree initialization
  * Event System, for inter-process communication
  * Interrupt manager, APIs to manage embedded interrupts
  * APIs for accessing value of tokens added to Token Manager
* CPC
  * Small improvement and bug fixes
* Security
  * Mbed TLS upgraded (to version 3.5.0)
* RAIL 5.0.0
  * Added support for collision detection feature on the EFR32xG25 parts
  * Added support for additional Coex TX and RX metrics events to RAIL coexistence utility
  * Updated some RAIL APIs to better prepare for future API changes while retaining backwards compile-time compatibility
* Other Components
  * Compilers upgraded (to GCC 12.2.1 and IAR 9.40.1)

PS: Also new versions for USB Device Stack 1.3.0.0 (as well as OpenThread version 2.5.0.0, Bluetooth 8.0.0, and Z-Wave 7.22.0.0):

https://www.silabs.com/documents/public/release-notes/usb-device-release-notes-1.3.0.0.pdf

**Comment by Nerivec** [comment]
https://github.com/Koenkk/zigbee2mqtt/discussions/23224
