### ISSUE TITLE
the coordinator doesn't respond to "Match Description Request"

### ISSUE THREAD

**Issue by msadeghz** [Koenkk/zigbee-herdsman#11]
Hi @Koenkk , 
I have a new zigbee device. it sends Match Description Request to the coordinator during join procedure. but the coordinator doesn't respond to it.
I use the latest version of CC2531 firmware and zigbee2mqtt. you can see the issue in below image:
![image](https://user-images.githubusercontent.com/22853649/61776491-61800380-ae10-11e9-8146-9532b7c69753.png)
the normal condition should be like below:
![image](https://user-images.githubusercontent.com/22853649/61776516-6fce1f80-ae10-11e9-9ea5-3409366e19fa.png)

**Comment by msadeghz** [comment]
do you mead I use zigbee-herdsman instead of zigbee-shephered? 
the Match Description Request is sent for cluster-id 6
![image](https://user-images.githubusercontent.com/22853649/61851644-c7ca5c00-aecc-11e9-8dd6-de6e1fb18830.png)

**Comment by Koenkk** [comment]
If you are on zigbee2mqtt 1.5.1 you are using zigbee-herdman (fork of zigbee-shepherd which im currently refactoring). 

If you want to solve it now you can try to do the required changes yourself, if not, I will look into it once refactor is completed.

**Comment by msadeghz** [comment]
OK

**Comment by msadeghz** [comment]
Hi again
![image](https://user-images.githubusercontent.com/22853649/62420482-2f8c5e00-b6a8-11e9-87bb-d093afa2ed1a.png)

the "match descriptor request" is like above. (infact the device wants to check the coordinator supports profile, input cluster and output clusters or not)
where can I handle the request? in the zigbee-shepherd? when I run `DEBUG=* npm start`, I can't see any thing when the node sends the "match descriptor request".

**Comment by msadeghz** [comment]
the issue is resolved.
I create an application in the coordinator (like ciepp) which have "ssIasZone" in server and client side and then my coordinator responds the "Match Descriptor Request" finely.
