### ISSUE TITLE
ZNP: Socket needed a keepalive option

### ISSUE THREAD

**Issue by xeno010** [Koenkk/zigbee-herdsman#112]
**Problem:**
If the remote peer does not disconnect the TCP connection properly (e.g. by crashing or wifi reconnect), the herdsman-znp will not notice. 
All incoming data from sensors (CCXXX -> tcp > zigbee2mqtt) is then lost because herdsman-znp thinks everything is okay (TCP connection is still open).
A socket error is only registered when data is sent from ZNP (zigbee2mqtt -> tcp -> CCXXX).

**Solution:**
One solution is to add a keepalive. I think 15sec is a good value.
see https://nodejs.org/api/net.html#net_socket_setkeepalive_enable_initialdelay

What do you think?

----
currently I still use socat to solve the problem:
```socat -d -d pty,link=/opt/zigbee_cc2530,raw,user=root,mode=777,echo=0 tcp:,reuseaddr,keepalive,keepidle=5,keepintvl=15,keepcnt=2```

**Comment by Koenkk** [comment]
Added a keep alive timeout of 15 seconds, thanks!
