### ISSUE TITLE
Can't open serial port on Windows 10

### ISSUE THREAD

**Issue by Arzachena** [Koenkk/zigbee-herdsman#120]
I'm running node-red on Windows 10. The node is node-red-contrib-zigbee (controller) which uses zigbee-herdsman. I have a Conbee II on port COM3.
When I run node-red I get:
 "4 Jan 15:08:54 - [info] [zigbee-shepherd:zigbee herdsman] connecting COM3 undefined"
followed by:
"4 Jan 15:09:11 - [error] [zigbee-shepherd:zigbee herdsman] Error while opening serialport 'Error: Opening COM3: Access denied'"
I have tried...
Changing to a different port. rebooting, reinstalling node-red, changing the port driver, etc, etc.
When I use a node called "node-red-node-serialport", I get no errors.
Any ideas?

**Comment by Koenkk** [comment]
Conbee is not supported, only TI cc devices.
