### ISSUE TITLE
About Zstack's mgmtNwkUpdateReq ID 

### ISSUE THREAD

**Issue by nraynaud** [Koenkk/zigbee-herdsman#1237]
There is a todo about an oddity in TI's numbering of a command:
```
            name: 'mgmtNwkUpdateReq',
            ID: 55, // TODO: 0x0038 => 56??
            type: CommandType.SREQ,
            zdoClusterId: ZdoClusterId.NWK_UPDATE_REQUEST,
```
https://github.com/Koenkk/zigbee-herdsman/blob/d84725bc22abe15d5ea3215b3a961fd6d65d22ff/src/adapter/z-stack/znp/definition.ts

It seems that somebody at TI had a bad day, the specification spacifies 0x38, but 0x37 has presumably been deprecated:
<img width="1136" alt="Screenshot 2024-11-15 at 03 09 33" src="https://github.com/user-attachments/assets/a7990866-98b2-442a-a506-da269cf70963">

but TI's document specifies 0x37:
<img width="797" alt="Screenshot 2024-11-15 at 03 08 46" src="https://github.com/user-attachments/assets/d7e70d4e-f7b4-46d0-bee2-9af3be7180d4">

and their code too:
https://github.com/TexasInstruments/simplelink-lowpower-f2-sdk/blob/main/source/ti/zstack/mt/mt.h#L322 

hope this helps.

**Comment by Koenkk** [comment]
Could you submit a PR to update the comment?
