### ISSUE TITLE
New Livolo switch and malformed packet

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee-herdsman#127]
I try to use new Livolo switch https://aliexpress.ru/item/4000385782177.html

Wireshark log [livolo_switch.zip](https://github.com/Koenkk/zigbee-herdsman/files/4073227/livolo_switch.zip)

But in log I see malformed packet when Livolo Gateway send command to turn switch on/off.
I try to repeat this action in converters:
```
    await entity.command('genOnOff', 'toggle', {}, {});
    const payload = {0x0001: {value, type: 0}};
    await entity.write('genPowerCfg', payload, {manufacturerCode: 0x1ad2, disableDefaultResponse: true});
```
And got result logs [livolo_switch_herdsman.zip](https://github.com/Koenkk/zigbee-herdsman/files/4073240/livolo_switch_herdsman.zip)

I can not repeat payload data for command. What we can do for this?

**Comment by kirovilya** [comment]
I can’t choose the type of value to send an array of zeros

**Comment by Koenkk** [comment]
What is the ID in wireshark of the on off command?

**Comment by kirovilya** [comment]
![image](https://user-images.githubusercontent.com/8360230/72617009-2424aa80-3949-11ea-82bc-695b6929f51a.png)
![image](https://user-images.githubusercontent.com/8360230/72617022-2850c800-3949-11ea-902f-d5398976a863.png)


401 and down...
425, 448, 498

**Comment by Koenkk** [comment]
I've created an example for the on and off: https://github.com/Koenkk/zigbee-herdsman/commit/dec27ed0b027671167d49b134945b4830bfbea24#diff-8158e442a03e3ab9574aeb1a2259d330R609 (requires latest herdsman)

so this would translate to:

```js
    await entity.command('genOnOff', 'toggle', {}, {});
    const payloadOn = {0x0001: {value: Buffer.from([1, 0, 0, 0, 0, 0, 0, 0]), type: 1}};
    const payloadOff = {0x0001: {value: Buffer.from([0, 0, 0, 0, 0, 0, 0, 0]), type: 1}};
    await entity.write('genPowerCfg', payloadOn OR payloadOff, {manufacturerCode: 0x1ad2, disableDefaultResponse: true});
```

**Comment by kirovilya** [comment]
Thank you, I will try it tomorrow

**Comment by kirovilya** [comment]
It is better now, but
![image](https://user-images.githubusercontent.com/8360230/72685992-e10d3780-3b00-11ea-83c0-faf82d1796ac.png)
frame header not equal...
switch not toggle :( 
[livolo_switch_herdsman2.zip](https://github.com/Koenkk/zigbee-herdsman/files/4083105/livolo_switch_herdsman2.zip)

**Comment by Koenkk** [comment]
Can you change https://github.com/Koenkk/zigbee-herdsman/blob/master/src/controller/model/endpoint.ts#L188 `Zcl.Direction.CLIENT_TO_SERVER` to `Zcl.Direction.SERVER_TO_CLIENT`, if this works I will provide a proper solution to pass it.

**Comment by kirovilya** [comment]
I've done everything. Now even the leading bits match. But switching does not work ... :(
Livolo may have done something tricky at the pairing stage that the device does not accept commands...
[livolo_switch_herdsman3.zip](https://github.com/Koenkk/zigbee-herdsman/files/4087355/livolo_switch_herdsman3.zip)

**Comment by kirovilya** [comment]
even reset the sequence numbers on the toggle command ...

**Comment by Koenkk** [comment]
Strange, it's really annoying that Livolo doesn't respect the ZCL, this makes it very hard to integrate.

**Comment by sjorge** [comment]
> Strange, it's really annoying that Livolo doesn't respect the ZCL, this makes it very hard to integrate.

So I guess the Livolo devices are also not zigbee certified?

**Comment by Koenkk** [comment]
@sjorge definitely not, in terms of zigbee compliance, these are the worst devices I've ever seen.
