### ISSUE TITLE
Online/offline state not reliable

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/zigbee-herdsman#13]
e.g: 
- https://github.com/Koenkk/zigbee2mqtt/issues/1801#issuecomment-517943708
- https://github.com/Koenkk/zigbee2mqtt/issues/1811

**Comment by Koenkk** [comment]
Removed online/offline state -> replaced with lastSeen.

**Comment by carldebilly** [comment]
I'll remove this completely from Zigbee2MqttAssistant.
