### ISSUE TITLE
Aqara Opple Switch support ( Model WXCJKG12LM ) new cluster

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee-herdsman#132]
new cluster 0xfcc0 for change working mode
![image](https://user-images.githubusercontent.com/8360230/73158962-6c388f80-40f6-11ea-99be-5cb3e0c54d4f.png)
now we can get all actions of all buttons

**Comment by kirovilya** [comment]
But when we change mode - we lost binding functional :(

**Comment by Koenkk** [comment]
Merged your pr, thanks!
