### ISSUE TITLE
Feature request: Logging levels

### ISSUE THREAD

**Issue by ristoavila** [Koenkk/zigbee-herdsman#137]
Would be nice to have logging levels similar to zigbee2mqtt or feature specific e.g.
ota_update
pairing
routing

With large networks at least I get lot's of messages and it annoying to trying to find out when the pairing starts and when its done if its done or if it even started.

These values also should be somehow set through the zigbee2mqtt by using mqtt message. Having an env variable to be set before you start zigbee2mqtt is also kind of annoying.

**Comment by sjorge** [comment]
I think 'categories' is a better name for the things you listed, they could be supplemental to the log levels we currently have.
