### ISSUE TITLE
node-red bindings?

### ISSUE THREAD

**Issue by podarok** [Koenkk/zigbee-herdsman#14]
Hi
Is there any documentation about API used?
I'd like to integrate this into node-red
Would be cool to have zigbee2mgtt nodes there.

**Comment by Koenkk** [comment]
Would you like to integrate zigbee2mqtt or zigbee-herdsman?

Note that I'm currently refactoring zigbee-herdsman so the API is not stable.

**Comment by hobbyquaker** [comment]
@podarok I'm working on https://github.com/hobbyquaker/node-red-contrib-zigbee and already use it in production since a few months. Maybe you wanna contribute :)
