### ISSUE TITLE
Re-execute certain commands when coordinator ieeeAddr changes

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/zigbee-herdsman#141]
https://github.com/Koenkk/zigbee2mqtt/issues/2987#issuecomment-590081385

Some commands contain `ieeeAddr` information. In case the `ieeeAddr` changes these commands should be executed again with the new `ieeeAddr`.

Currently I can think of the following commands:
- Binds
- iAS enrolment

**Comment by Kryzek** [comment]
I think this is kind of related/dependant to this https://github.com/Koenkk/zigbee-herdsman/issues/104
