### ISSUE TITLE
Lost all devices when changed CC2652R (same devboard)

### ISSUE THREAD

**Issue by ex3ndr** [Koenkk/zigbee-herdsman#143]
I replaced one devboard with CC2652R to the exactly same devboard with a same chip and instantly lost all devices. 

There are new methods for some backups from device itself, do i need to do something beside keeping file specified in databasePath?

**Comment by Koenkk** [comment]
You also need to have the `data/coordinator_backup.json`, zigbee2mqtt will automatically restore if that file is present.
