### ISSUE TITLE
Where is network states retained?

### ISSUE THREAD

**Issue by the729** [Koenkk/zigbee-herdsman#16]
Hi,

I'm fairly new to Zigbee and ZNP. I wonder where is network states retained in a system of zigbee-shephard/herdsman + ZNP module? 

I know zigbee shephard has some states saved in a local json file. Is that all? Is it possible to transparently replace the ZNP module with a new one, while still able to maintain the network?

**Comment by Koenkk** [comment]
I know zigbee shephard has some states saved in a local json file. Is that all? 
=> yes

Is it possible to transparently replace the ZNP module with a new one, while still able to maintain the network?
=> https://www.zigbee2mqtt.io/information/what_does_and_doesnt_require_repairing.html

Note that the issue tracker is meant for tracking bugs, for questions please use http://zigbee2mqtt.discourse.group/ or https://discord.gg/dadfWYE.
