### ISSUE TITLE
CC2652 - dongle ?

### ISSUE THREAD

**Issue by osos** [Koenkk/zigbee-herdsman#174]
Anyone know is this is stable:

Small cc2652 usb dongle:  https://electrolama.com/projects/zig-a-zig-ah/

Looks promising.

**Comment by Koenkk** [comment]
Yes it's stable (my production network is running on it). It's not yet available but hopefully soon (I've got one from the creator himself). Once it is for a reasonable price this will be the recommended adapter.

**Comment by osos** [comment]
Seems available on Tindie:

https://www.tindie.com/products/electrolama/zzh-cc2652r-multiprotocol-rf-stick/

Shipping is a bit high, otherwise acceptable price compared to Conbee

**Comment by klausdm** [comment]
God dammit. Just received the TI CC1352P-2 dev 🙁
