### ISSUE TITLE
Increase retry count on pairing for SmartThings sensor

### ISSUE THREAD

**Issue by jhenkens** [Koenkk/zigbee-herdsman#176]
https://github.com/Koenkk/zigbee-herdsman/blob/master/src/controller/model/device.ts#L498

I'm not sure if the comment on this code is implying this wait period is going to go away entirely (and thus, the success/error messages below as well). But for the SmartThings sensors, if we double this attempt count, we get successful pairings per the log message, rather than "failed to Interview" combined with a "successfully configured".

I'm not sure specifically if this changes long term behavior of the pair or not, but it seems in my experience, my Smart Things Multi Sensor (2018 variety) sends the pair request about 2 seconds after we break out of this loop. Increasing the retry to 20 resulted in "Successful Interview" for me.

**Comment by Koenkk** [comment]
done, did two things
- Changed no. of attempt to 20
- Increased wait period between attempts to 500 ms

This should give the device 10 seconds to changes it's zoneState. 

Thanks!
