### ISSUE TITLE
Remove database as cause for async

### ISSUE THREAD

**Issue by onnlucky** [Koenkk/zigbee-herdsman#19]
At the moment, calls like `getDevice` are async, because it might query the database. Often it doesn't as it uses `Device.lookup`. But herdsman could operate with the in-memory data structures as the source of truth, only synced to disk in a best-effort manner.

That would make the path between receiving message from a device to sending a message in response to another device a single tick of the runloop.

If I am not mistaken, only groups and devices are stored directly, the rest (eg endpoints) are stored via the device. It would be even nicer to provide a default storage adapter, but allow libraries to bring an alternative implementation.

It would also be nice if the data store supports custom properties. So that users of the library have a place to store properties like the device friendly name without having to maintain a parallel data store.

**Comment by Koenkk** [comment]
Database is synchronous know (zigbee-herdsman 0.7.0)
