### ISSUE TITLE
Custom error class for Zcl.Status

### ISSUE THREAD

**Issue by allofmex** [Koenkk/zigbee-herdsman#198]
Thanks for implementing zcl error status handling (by throwing Error in case of non-success status):

https://github.com/Koenkk/zigbee-herdsman/blob/cc37a20fcec32282027b35d2c8f3f0533bcc4f49/src/controller/model/endpoint.ts#L255

This solved my main issue in [PR #114 Add optional zcl status result to endpoint write and command actions ](https://github.com/Koenkk/zigbee-herdsman/pull/114)
Using an exception may even be the better way than my suggest :-)

One more wish:
Can we have custom errors instead of a general?

```
class ZclStatusError extends Error {
  constructor(statusCode) {
    super(`Status '${Zcl.Status[statusCode]}'`);
    this.statusCode = statusCode; // integer
  }
}
```
This would allow better handling on client side than to back-parse statusCode from string like "Status 'UNSUPPORTED_ATTRIBUTE'"
```
if (err instanceof ZclStatusError) {
    if (err.statusCode == 1) {
        ...
    }
} else {
    // not status related error
}

```
I am still dreaming of a (half)-automated template generating for unimplemented devices. For this we need the error status code.

**Comment by Koenkk** [comment]
Implemented!
