### ISSUE TITLE
EZSP adapter implementation

### ISSUE THREAD

**Issue by mitchsw** [Koenkk/zigbee-herdsman#208]
Has this project considered adding an EZSP adapter implementation? I imagine this could enable support for the following devices: https://github.com/zigpy/bellows#hardware-requirement (I am particularly interested in HUSBZB-1 for a neat Home Assistant setup).

**Comment by Koenkk** [comment]
Yes, see https://github.com/Koenkk/zigbee-herdsman/issues/168#issuecomment-667953971
