### ISSUE TITLE
Failed to Start Zigbee

### ISSUE THREAD

**Issue by mathieusibilla** [Koenkk/zigbee-herdsman#210]
Hi,

I tried to look in the previous issues posted here and tried a few of the solutions mentioned but nonw seems to work. 
I'm a HomeAssistant user and want to implement Z2M in order to use some new Zigbee devices (I already have Hue lights and sensors running off the Philips sqaure bridge). 
I have installed the Z2M add-on following thre instructions (https://github.com/danielwelch/hassio-zigbee2mqtt) and when I try to start the add-on I get the following issue:

[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-08-14T10:38:52: PM2 log: Launching in no daemon mode
2020-08-14T10:38:53: PM2 log: App [npm:0] starting in -fork mode-
2020-08-14T10:38:53: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.3 start /zigbee2mqtt-1.14.3
> node index.js
Zigbee2MQTT:info  2020-08-14 10:39:27: Logging to console and directory: '/share/zigbee2mqtt/log/2020-08-14.10-39-27' filename: log.txt
Zigbee2MQTT:info  2020-08-14 10:39:31: Starting Zigbee2MQTT version 1.14.3 (commit #unknown)
Zigbee2MQTT:info  2020-08-14 10:39:31: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-08-14 10:40:12: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-08-14 10:40:12: Failed to start zigbee
Zigbee2MQTT:error 2020-08-14 10:40:12: Exiting...
Zigbee2MQTT:error 2020-08-14 10:40:12: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.14.3/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:87:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.14.3/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm 
ERR! zigbee2mqtt@1.14.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

#####
This is the confirguration I have set for the add-on:

data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto:1883'
  user: mqtt
  password: mqttpassword
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00014EF519-if00
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: true

#####
I'am running HassOS 4.12on a Rpi3.

If anybody can help it would be very appreciated 
Thanks

**Comment by insipiens** [comment]
The port doesn't look correct. Can you run the following command to identify which port 

`ls -l /dev/serial/by-id`

Should produce an output like this:
`total 0
lrwxrwxrwx 1 root root 13 Sep  6 15:56 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D95B28-if00 -> ../../ttyACM0`

in the above case the port in your configuration.yaml would be based on the _../../ttyACMO_
So like this....
`  port: /dev/ttyACM0`

Make a copy of your yaml before changing it in case you need to revert to it.
