### ISSUE TITLE
Trying to add a new adapter

### ISSUE THREAD

**Issue by Florian-Krauss** [Koenkk/zigbee-herdsman#216]
I'm currently working on implementing a new adapter/coordinator to zigbee2mqtt, that is neither from deconz nor from z-stack. Is there documentation on how I can do that or does anyone know what exactly needs to be defined in the code to make it work? 
The device I want to use as the adapter is an AP-515-RW from HPE aruba.

**Comment by Koenkk** [comment]
To add support for a new adapter the following interface has to be implemented: https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/adapter.ts

E.g. implementation for z-stack: https://github.com/Koenkk/zigbee-herdsman/tree/master/src/adapter/z-stack

**Comment by Florian-Krauss** [comment]
So it's possible to use the z-stack Code for a non-z-stack adapter?

**Comment by Koenkk** [comment]
No, but you can use it as a new example when adding support for a new adapter.

**Comment by Florian-Krauss** [comment]
Ok, I will try, thank you.
