### ISSUE TITLE
Write for 'BUFFER' not available

### ISSUE THREAD

**Issue by nlaurie** [Koenkk/zigbee-herdsman#243]
Trying to use the library 0.13.18 with a CC2531 directly not through zigbee2mqtt, 
using recommended latest firmware

When calling controller.start(); 
receiving an error Write for 'BUFFER' not available

attached is the debug output.  
[Debug.txt](https://github.com/Koenkk/zigbee-herdsman/files/5419024/Debug.txt)

Seems like there is an empty buffer when doing something with a group.  Not sure why it went from working to not working.  I cleared all the settings and restarted and the Database.db file is not getting created.  I'm assuming this is due to failed start.  

One more thing I when running zigbee2mqtt it seems to start up as expected.

**Comment by Koenkk** [comment]
I've looked at your log but cannot find the issue. Can you provide a minimal example to reproduce the issue?
