### ISSUE TITLE
UnhandledPromiseRejectionWarning with Deconz Adapter

### ISSUE THREAD

**Issue by scootec** [Koenkk/zigbee-herdsman#250]
I am receiving the follow stack trace semi regularly. Below is once instance of the error:

`(node:358) UnhandledPromiseRejectionWarning: Error: Read 0x0017880104dfff37/11 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (no response received)
    at DeconzAdapter.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:552:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:25:65)
(node:358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

If I am reading the trace right, [this is](https://github.com/Koenkk/zigbee-herdsman/blob/f82073810f68482ce4b33dabec58da8b6add02a0/src/adapter/deconz/adapter/deconzAdapter.ts#L552) the problem line in deconzAdapter.ts.

Should this catch block be switched to a `Throw new Error` as per [this commit](https://github.com/Koenkk/zigbee-herdsman/commit/17dc97a5fcd8ad61625f56e2ca177ca8b20301ef#diff-e287278735156a983a1ca18677f8f6580622520aa743a7a9c191db0ed111f20d)?

My setup is as follows:
- Zigbee2mqtt running as Home Assistant Add-on.
- `0x0017880104dfff37 ` is a Phillips 8718696449691.
- Zigbee2mqtt 1.16.0

Thanks for the help!

**Comment by Koenkk** [comment]
@ChrisHae can you check this?
