### ISSUE TITLE
Not correct join Gaz Detector SGMHM-I1 and Siren SRHMP-I1 via Zigate in Iobroker...

### ISSUE THREAD

**Issue by itProfi** [Koenkk/zigbee-herdsman#252]
Good day! I try join device Gaz Detector SGMHM-I1 via Zigate in Iobroker...and have some errors..
How i can correct this situation?
![Скриншот 08-11-2020 123830](https://user-images.githubusercontent.com/6728198/98462074-5b0eca00-21c2-11eb-952e-0ddc97fc3bef.jpg)
![Скриншот 08-11-2020 124206](https://user-images.githubusercontent.com/6728198/98462075-5c3ff700-21c2-11eb-8b0a-32fa3e32b687.jpg)
![Скриншот 08-11-2020 123927](https://user-images.githubusercontent.com/6728198/98462077-5c3ff700-21c2-11eb-99ac-7ba2213961bd.jpg)
Аfter restart adapter in Iobroker, device like ok, but not work properly...
[iobroker.2020-11-08.log](https://github.com/Koenkk/zigbee-herdsman/files/5506125/iobroker.2020-11-08.log)

**Comment by itProfi** [comment]
Same problem with smart siren HS2WD-E (it's not "vendor":"HEIMAN", it's russian market Tricolor)
![Скриншот 08-11-2020 130842](https://user-images.githubusercontent.com/6728198/98462215-8f36ba80-21c3-11eb-9d4e-7545d5c2e3cb.jpg)
![Скриншот 08-11-2020 130619](https://user-images.githubusercontent.com/6728198/98462217-8fcf5100-21c3-11eb-9426-5832099f924d.jpg)
[iobroker.2020-11-08_siren.log](https://github.com/Koenkk/zigbee-herdsman/files/5506136/iobroker.2020-11-08_siren.log)

**Comment by Koenkk** [comment]
With what adapter is this?

**Comment by itProfi** [comment]
JN5169 with zigate coordinator firmware

**Comment by Koenkk** [comment]
The `Cannot read property length of undefined` indicates an error in the adapter code. @G1K or @kirovilya can you look at this?

**Comment by itProfi** [comment]
@Koenkk In my case, i see, that error is in OTA Update...how i can disable temporary  this?

**Comment by Koenkk** [comment]
This functionality cannot be disabled currently.

**Comment by itProfi** [comment]
> This functionality cannot be disabled currently.

And how i can correct this error?

**Comment by Koenkk** [comment]
I expect some fixes are required in the adapter code (https://github.com/Koenkk/zigbee-herdsman/issues/252#issuecomment-723579075)

**Comment by itProfi** [comment]
Today i try only xiaomi gateway with jn5169 and zigbee2mqtt and thats all! Not IOB..I allready ask @kirovilya , he don't no, what do with this error. I upgrdae zigbee2mqtt to 1.6.1 and give another error - 
![Скриншот 09-11-2020 191009](https://user-images.githubusercontent.com/6728198/98570665-bb863000-22c4-11eb-8d11-5be7cfd40252.jpg)
![Скриншот 09-11-2020 195010](https://user-images.githubusercontent.com/6728198/98570744-cfca2d00-22c4-11eb-8ce3-933f3547ae88.jpg)

**Comment by itProfi** [comment]
@Koenkk @kirovilya says, that he don't no, what's the problem...last error is 
![Скриншот 12-11-2020 160440](https://user-images.githubusercontent.com/6728198/98944125-9af6e980-2501-11eb-8405-587a97934a30.jpg)
 in Iobroker

**Comment by itProfi** [comment]
@Koenkk is it possible correct this?

**Comment by Koenkk** [comment]
@itProfi I cannot fix this, has to be fixed in the adapter code (https://github.com/Koenkk/zigbee-herdsman/issues/252#issuecomment-724129233)

**Comment by itProfi** [comment]
@Koenkk No, i has lastest code for this adapter and it's not work. @kirovilya says, that he not correct this for at least one more month (( If you want, close this issue..

**Comment by G1K** [comment]
I am working on this problem. This is where I came to.

1. We need a separate queue on the APDU, when using a common queue and waiting for a message 0x8000, messages are partially sent to the network. 
2. When pairing, a lot of requests are often generated, for example, on FreePad 20 endpoint + 20 bind. If you use a sequential queue and wait for a message from the network, it works more stable, but still, when using equal requests, the adapter hangs and does not allow messages to be sent to the network. https://github.com/fairecasoimeme/ZiGate/issues/348 (This was always the case before firmware 3.1d for incoming messages). The solution is still unknown, I can only suggest rebooting the adapter, but the number of instances for different firmware is different and I have not yet figured out how to find out when they are over. 
3. The fix of expectations from this PR does not wait for an answer, although it is needed and the herdsman wants to get a result.  https://github.com/Koenkk/zigbee-herdsman/pull/247/files#diff-12256257d3beef78fe73fdda606b50fbb139127f642a50b74894e21eff30414aR546-R547

As I finish the implementation I will do a PR, while there are only temporary sketches.

// I want to make the most of the adapter, and I don't want to put all messages in the general queue if one of the devices falls asleep and does not receive messages.

**Comment by itProfi** [comment]
@G1K all do!
