### ISSUE TITLE
Please remove the bloat from npm-shrinkwrap before publishing the package

### ISSUE THREAD

**Issue by geogeim** [Koenkk/zigbee-herdsman#260]
right now node_modules for this package has 510 dependencies, totaling 123 mb of useless packages like babel and other stuff because you're including all the dev dependencies in npm-shrinkwrap.json

before publishing the package to npm please do this:
```
npm prune --production
npm shrinkwrap
```

also it would be nice to update your .npmignore to exclude useless folders like .github, temp, etc.

**Comment by Koenkk** [comment]
@nurikk can you take a look at this?

**Comment by nurikk** [comment]
> @nurikk can you take a look at this?

Sure
