### ISSUE TITLE
Implementation ZdpFrame parser

### ISSUE THREAD

**Issue by G1K** [Koenkk/zigbee-herdsman#297]
It would be ideal to implement by analogy with ZclFrame.fromBuffer => ZdpFrame.fromBuffer .
This would reduce the code in the Deconz / Zigate adapter and improve the readability of the code.

**Comment by Koenkk** [comment]
Agree! With this we can get rid of e.g. node descriptor, bind calls in the adapter

**Comment by Hedda** [comment]
Should this have been closed?

**Comment by Hedda** [comment]
hould this have been closed?
