### ISSUE TITLE
SOFTWARE_FAILURE error when setting up device with multiple endpoints

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee-herdsman#358]
I am currently writing a converter for a new device.

When creating the configure entry for genOnOff endpoints, I get the following error:

```
Zigbee2MQTT:error 2021-05-06 09:32:21: Failed to configure '0x04cf8cdf3c88d48a', attempt 1 (Error: ConfigureReporting 0x04cf8cdf3c88d48a/2 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'SOFTWARE_FAILURE'),
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:196:23),
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:419:26),
    at Generator.next (<anonymous>),
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)),
```

This entry works:

```javascript
    configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(device.getEndpoint(1));
    }
```

This entry fails:

```javascript
    configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(device.getEndpoint(1));
            await reporting.onOff(device.getEndpoint(2));
    }
```

This is with a meta setting of: `meta: {multiEndpoint: true},`

I have also tried adding `await utils.sleep(1000);` as suggested by @Koenkk between each config entry but this also fails - It also fails when configuring reporting via the gui - Interestingly, the genOnOff endpoints aren't listed as available however, in the clusters section, they clearly are..?

Device database entry (in case it is useful):
`{"id":2,"type":"Router","ieeeAddr":"0x04cf8cdf3c88d48a","nwkAddr":14342,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.switch.n4acn4","epList":[1,2,242,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,2,3,4,5,6],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.switch.n4acn4","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":26,"stackVersion":2,"hwVersion":1,"dateCode":"06-18-2020"}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":26,"stackVersion":2,"hwVersion":1,"dateCode":"06-18-2020","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1619433552334}`

**Comment by Koenkk** [comment]
This is likely not a zigbee-herdsman issue but rather an issue of the device itself. 

- Does reporting of the state when controlled manually also work with the reporting.onOff on endpoint 1 and 2?
- If not, you need to sniff the traffic when pairing this device with the original gateway to see how it works there. https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html
