### ISSUE TITLE
Cleanup unknown viessman attributes

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman#366]
https://github.com/Koenkk/zigbee-herdsman/blob/ef3d96c9ed4b75c57af1fc71e618add0f1c3064e/src/zcl/definition/cluster.ts#L1899

@Koenkk In the end I only managed to figure out 2 of custom attributes the viessman TRV sends.

I think it would be better to remove the unknown ones to keep the file clean and compact. Good idea? Bad idea?

**Comment by Koenkk** [comment]
Good idea, please create a PR :smile:

**Comment by sjorge** [comment]
Will do, I'll rename viessmannCustom0 to viessmannWindowOpen as that one is actually in use and it indicates window open and drop all other viessmannCustomX's.

**Comment by sjorge** [comment]
Done https://github.com/Koenkk/zigbee-herdsman/pull/367

**Comment by Koenkk** [comment]
Merged, thanks
