### ISSUE TITLE
v0.13.96 has introduced a bug with "Cannot read property 'disableLED' of null"

### ISSUE THREAD

**Issue by wojciechczerniak** [Koenkk/zigbee-herdsman#374]
I guess my USB dongle does not have such option as `disableLED`.
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'disableLED' of null
    at Controller.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:244:77)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/controller/controller.js:24:58)
```
Introduced in https://github.com/Koenkk/zigbee-herdsman/commit/8d50ba0cd78369b7f93911f00d6a47f7972667df

https://github.com/Koenkk/zigbee-herdsman/blob/8d50ba0cd78369b7f93911f00d6a47f7972667df/src/controller/controller.ts#L237-L239

I'm using this package in Homebridge with: https://github.com/madchicken/homebridge-zigbee-nt which does not lock the deps version.

EDIT: Unless, `homebridge-zigbee-nt` overwrites adapter options 🤔 

EDIT 2: Right. https://github.com/madchicken/homebridge-zigbee-nt/blob/0a1b568d2a7c4120cdce7ecef207536b356ce2b2/src/zigbee/zigBee-controller.ts#L126 and since https://github.com/Koenkk/zigbee-herdsman/commit/8d50ba0cd78369b7f93911f00d6a47f7972667df `zigbee-herdsman` assumes it will be an object `{ disableLED: false }` 😞

**Comment by Koenkk** [comment]
Not a zigbee-herdsman bug since the adapter option is mandatory. https://github.com/madchicken/homebridge-zigbee-nt/blob/0a1b568d2a7c4120cdce7ecef207536b356ce2b2/src/zigbee/zigBee-controller.ts#L126 should be changed to `adapter: {},`
