### ISSUE TITLE
bind tracking

### ISSUE THREAD

**Issue by hobbyquaker** [Koenkk/zigbee-herdsman#40]
Hey Koenkk, I think a new Issue for discussions around the bind tracking makes sense :-)

Right now I'm doing the tracking in the device.meta, looks like this:
```
"binds":[{"endpoint":1,"cluster":"genOnOff","targetType":"endpoint","targetDevice":"0x0017880102fe0180","targetEndpoint":11}]
```

Should we move that to the Endpoint Object instead? What do you think of the scheme itself? Using a Set instead of an Array? I think a Set will not offer an advantage as it will not prevent adding to Objects with same content. So right now I'm using a construct like this
```javascript
if (!device.meta.binds.find(b => {
    return b.endpoint === bind.endpoint &&
            b.cluster === bind.cluster &&
            b.targetDevice === bind.targetDevice &&
            b.targetEndpoint === bind.targetEndpoint;
})) {
    device.meta.binds.push(bind);
    device.save();
}
```
to prevent adding the same bind more than once. Do you have a more elegant suggestion for this?

**Comment by Koenkk** [comment]
This indeed should be moved to the endpoint, as you bind an endpoint not a device.

That code below looks good, however don't save this info in the `meta` but rather create a new property on `endpoint` called `binds`.

**Comment by hobbyquaker** [comment]
A first try, could you pls review?
https://github.com/hobbyquaker/zigbee-herdsman/commit/1c4fee6295ee8df71b96f8d6ec746adb4946a628

**Comment by Koenkk** [comment]
Looks good, can you make a PR? Then we will work further from there.

**Comment by hobbyquaker** [comment]
will do asap.
