### ISSUE TITLE
Using "Install Code" to pair devices

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee-herdsman#420]
First encountered a device that has an Install Code - rotary switch Aqara H1.
We need to learn how to pair a such devices.
As I understand it, when starting pairing, we need to specify the scanned key "Install Code".

![photo_2021-09-15_19-24-49 (2)](https://user-images.githubusercontent.com/8360230/133561297-430d97d1-3cae-462c-bcb6-9a1a915a51ec.jpg)
![photo_2021-09-15_19-24-49](https://user-images.githubusercontent.com/8360230/133561302-0c30501f-232b-48c7-8676-d513695f5b87.jpg)
![photo_2021-09-16_09-29-32](https://user-images.githubusercontent.com/8360230/133561306-322bafa8-c6fa-42b2-96b3-10e909d2bc56.jpg)

**Comment by MattWestb** [comment]
Look in Zigpy / ZHA github they have implanting it for some coordinator (EFR32 and perhaps TI) but i have not testing it then i dont have devices that using it.

**Comment by kirovilya** [comment]
found issue for z-stack https://github.com/zigpy/zigpy-znp/issues/29 and ezsp https://github.com/zigpy/bellows/issues/292
I continue to looking

**Comment by MattWestb** [comment]
Bellows CLI can joining with install code and its starting here:
https://github.com/zigpy/bellows/blob/a15b54fc2275a8bb603383062b5d8e8fe562e18e/bellows/cli/application.py#L73

If i remember right is adding the install code as one Trust center Link Key and is being updated if the Zigbee 3 device like updating the TC-Link key.

I think its one good start for looking at the code wot they is doing.

**Comment by sjorge** [comment]
Most hue/innr/tint/osram bulbs have them too, the format is always different sadly, but it usually include a key and other data.

https://github.com/Koenkk/zigbee2mqtt/discussions/8498 Has a few of them
