### ISSUE TITLE
Add adapater support BV 2010/10 (ZigBee USB dongle)

### ISSUE THREAD

**Issue by Summer88** [Koenkk/zigbee-herdsman#441]
Hi, 
I've tried out the BV 2010/10 (ZigBee USB dongle) with openhab it works out of the box with zigbee binding.

I need to get it work with zigbee2mqtt, but this one isn't actually supported: https://github.com/Koenkk/zigbee2mqtt/issues/9151

Here the specifications: https://bv.smabit.eu/index.php/smart-home-produkte/zb-funkstick/

May I ask you if there's a chance to add it  to the supported devices list?

I have the adapter available, can I try out to follow some tutorial to do it, and send you logs?

**Comment by MattWestb** [comment]
You need updating the firmware then Magenta and Co is running one old version on it.
Z2M for EZSP is needing protocol version 8.
Gary have cooked one working version but only one user have trying it  and its looks working OK https://github.com/grobasoz/zigbee-firmware/issues/15.

**Comment by Hedda** [comment]
As Matt noted, you will need to upgrade the EmberZet firmware on so it will support newer EZSP version 8.

Here are another links discussing  upgrading firmware Bitron Video/Smabit BV AV2010/10 USB-Stick with Silicon Labs Ember ETRX3587/EM3587:

https://github.com/zigpy/bellows/issues/348

Then after having upgraded firmware see https://github.com/Koenkk/zigbee-herdsman/issues/319 for other things related to EZSP and Z2M see this issue for now.

PS: Note that it is generally a bad idea to start using a Silicon Labs based adapter with old obsolete chips Silabs like the ETRX3587/EM3587 with Z2M, as not only will that hardware not get any newer firmware releases any longer, but the initial EZSP support in Z2M is still experimental and currently no developers are specifically working on making that initial EZSP more stable.
