### ISSUE TITLE
Rename all Tuya manu-speicific cluster commands

### ISSUE THREAD

**Issue by hacker-cb** [Koenkk/zigbee-herdsman#466]
Need to rename all existing Tuya commands and add new commands according [official Tuya commands documentation](https://developer.tuya.com/en/docs/iot-device-dev/tuya-zigbee-universal-docking-access-standard?id=K9ik6zvofpzql#subtitle-6-Private%20cluster).

Previous [discussion](https://github.com/Koenkk/zigbee-herdsman/commit/e0b6ceaeca24ede57930f2552b2332b7108ca211).

Other Tuya  links:

- [UART Protocol for Zigbee Three-level Architecture](https://developer.tuya.com/en/docs/iot/zigbee-module-uart-protocol?id=Ka3hdzgitg4kh#title-4-Frame%20format%20description)

**Comment by hacker-cb** [comment]
@Koenkk of cause this will break compatibility at leat between `herdsman` and `converters`.

So, please confirm that you are ready to that :)

**Comment by Koenkk** [comment]
@hacker-cb I will make sure to merge the prs at the same time.
