### ISSUE TITLE
Philips Hue Dimmer Switch Not Working / Intermittent Issue

### ISSUE THREAD

**Issue by thehaxxa** [Koenkk/zigbee-herdsman#51]
This issue still persists in herdsman, whats the best way to go about debugging this: https://github.com/Koenkk/zigbee-shepherd-converters/issues/637

**Comment by Koenkk** [comment]
Did you try https://github.com/Koenkk/zigbee-shepherd-converters/issues/637#issuecomment-535517509?

I will close this; let's keep this discussion in one thread (https://github.com/Koenkk/zigbee-shepherd-converters/issues/637)
