### ISSUE TITLE
Can we use Xbee S2C (and similar) radios with this?

### ISSUE THREAD

**Issue by alfsolli** [Koenkk/zigbee-herdsman#58]
Digi's devices, like mentioned above, or is this a cc253x with custom firmware only? 

I ask because I use them with node-red-contrib-xbee package and custom flows. They have great range, easy to work with (uart), and comes in a 63mW package, with possibility to use external antennas.

**Comment by Koenkk** [comment]
Not yet but this can be done by implementing the following interface (https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/adapter.ts).
