### ISSUE TITLE
Support NodeJS 6

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee-herdsman#6]
For use in the iobroker project, I would like to support nodejs starting from 6.
Therefore, I propose to rewrite the async-functions.

**Comment by Koenkk** [comment]
I understand however nodejs 6 is not maintained anymore, I would suggest to update to nodejs 10 (as support for nodejs 8 will also drop in the begin of next year).

https://github.com/nodejs/Release

**Comment by kirovilya** [comment]
This is the recommended version, but there are already many installations for version 6. :(
ok. thank
