### ISSUE TITLE
please support Osram Device with modelID 'Plug Z3'

### ISSUE THREAD

**Issue by Matten-Matten** [Koenkk/zigbee-herdsman#61]
https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/42

```
		// LEDVANCE
	AC10691_cmdOn: {
        cluster: 'genOnOff',
        type: 'commandOn',
        convert: (model, msg, publish, options) => {
            return {action: 'on'};
        },
    },
    AC10691_cmdOff: {
        cluster: 'genOnOff',
        type: 'commandOff',
        convert: (model, msg, publish, options) => {
            return {action: 'off'};
        },
    },
	//
```
fehlt in der 

> fromZigbee.js

Gruß
Matten

**Comment by Matten-Matten** [comment]
Moin, ich hab ein paar fragen bezüglich der Konfiguration und Bedienung.
Bei mir taucht folgender Fehler auf.
`configure failed 0xf0d1b80000125523 (LEDVANCE Plug 1) Cannot read property 'bind' of undefined`

was ist dieses 'bind' und was konfiguriere ich dort genau? Ich stehe da irgendwie aufm schlauch. 
![Node-RED _ bind](https://user-images.githubusercontent.com/32074970/66471677-0adbaa80-ea8c-11e9-9746-063aaca318d8.png)

Kannst du mir das erläutern? Danke im voraus.

Gruß
Matten Matten

**Comment by Koenkk** [comment]
Please make a pr for https://github.com/Koenkk/zigbee-shepherd-converters
