### ISSUE TITLE
Support for XBee s2c?

### ISSUE THREAD

**Issue by skandragon** [Koenkk/zigbee-herdsman#64]
Can you give me an idea on how difficult it may be to add a driver for the XBee s2c module?  It has some characteristics I find more useful than the typical USB sticks for the TI chips, such as various power and antenna options.

I have quite a bit of familiarity with the module, but I don't have a lot of knowledge on how much the cc chips currently handle.  The XBee has router/endpoint/coordinator modes, and has a fairly simple but low level API to send and receive various frames, and pass through most (perhaps not all) ZDO frames.

**Comment by Koenkk** [comment]
I'm not familiar with the device but it basically comes down to implementing this interface: https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/adapter.ts
