### ISSUE TITLE
Environment variable for debugging: DEBUG

### ISSUE THREAD

**Issue by mihmig** [Koenkk/zigbee-herdsman#655]
The variable name is too general: "DEBUG",  which conflicts with the Spring framework (if applications on it run on the same machine) and possibly other software.

Is it possible to rename it, for example, to ZIGBEE_HERDSMAN_DEBUG?

**Comment by Koenkk** [comment]
This comes from https://www.npmjs.com/package/debug, you should set it only for the Zigbee2MQTT process, not others (such that you don't get the conflicts)
