### ISSUE TITLE
PM2.5 cluster is not actually heiman specific

### ISSUE THREAD

**Issue by peterkappelt** [Koenkk/zigbee-herdsman#667]
Hi, this issue is related to another thread (https://github.com/Koenkk/zigbee2mqtt/issues/16717). We're trying to get the new IKEA air quality sensor up and running.

Currently, zigbee cluster 0x42A is specified as `heimanSpecificPM25Measurement`. However it isn't manufacturer specific at all - it is a normal cluster as specified in the ZCL spec (chapter 4.13). That's a problem now though, since there is a "manufacturerCode" given for this cluster that prevents messages with the IKEA manufacturer code coming through.

https://github.com/Koenkk/zigbee-herdsman/blob/2d1c453faf889afe57533778abf30fb9f074a1e9/src/zcl/definition/cluster.ts#L4589

My naive approach would be:
* simply renaming this cluster to "pm25Measurement" and renaming all references in zigbee-herdsman-convertes as well
* removing the manufacturerCode spec, since it isn't manufacturer specific at all

I'm not too familiar with zigbee-herdsman's architecture though. Are those two steps sufficient (would be happy to provide a PR then) or will we break something by renaming the cluster and removing the manufacturer code? 

Cheers!

**Comment by Koenkk** [comment]
Sounds good, I don't expect any issues. Please create a pr 😄
