### ISSUE TITLE
Zigbee Device PowerSource wrong Mapping for Konke Devices

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee-herdsman#71]
Hi @Koenkk 
It seem that your Power-Source Mapping seem to be wrong or the End-Device from Konke seems to be report wrong Power-Source-Value ``[34mzigbee2mqtt:debug[39m 2019-10-13T18:36:52: Received Zigbee message from 'konke_motion_1', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE14010402000D","manufacturerName":"Konke","powerSource":0}' from endpoint 1 with groupID 0``.
With this i get ``Unknown`` as Result but we know the Device use Battery :)

**Comment by Koenkk** [comment]
The value reported by Konke is wrong:

![image](https://user-images.githubusercontent.com/2892853/66810165-f76a8c80-ef2e-11e9-87e9-34a76fe16a4b.png)

**Comment by tb-killa** [comment]
hm. i thought this .. damn... i think konke doesnt patch them quickly.
okay we have to live with this fault at this time.
thanks a lot :)
