### ISSUE TITLE
Improve endpoint->configureReporting to handle manufacturer specific clusters/attributes

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman#717]
https://github.com/Koenkk/zigbee-herdsman/pull/712#issuecomment-1580084643

We should include some extra info so we correctly identify which manufacturer cluster and or attribute was configured.

**Comment by sjorge** [comment]
@Koenkk is the TS refactor of zhc done?

**Comment by Koenkk** [comment]
No not yet, I became a father a few weeks ago so I have less time to spend (so don't expect it to be done soon)

**Comment by sjorge** [comment]
> No not yet, I became a father a few weeks ago so I have less time to spend (so don't expect it to be done soon)

First of all, Congratulations! Can we add the do not stale label to this issue, so it doesn't get closed.
