### ISSUE TITLE
after Update from 1.8.06 to 1.8.12 Device with no States

### ISSUE THREAD

**Issue by Toysman** [Koenkk/zigbee-herdsman#733]
After updating to 1.6.12 my Lidl HG06492C has errors.

zigbee.0 | 165228 | 2023-07-09 17:50:43.364 | error | Device 0x588e81fffef96cc1 "HG06492C" not described in statesMapping.
-- | -- | -- | -- | --

![Bildschirmfoto 2023-07-09 um 17 30 42](https://github.com/Koenkk/zigbee-herdsman/assets/76917387/2daa77ba-49cf-400b-8e8b-9f12dd0f5657)

Also an error in my Log
zigbee.0 | 165228 | 2023-07-09 17:55:20.283 | info | List  of port:  [{"path":"/dev/ttyS0"},{"path":"/dev/ttyS1"},{"path":"/dev/ttyS10"},{"path":"/dev/ttyS11"},{"path":"/dev/ttyS12"},{"path":"/dev/ttyS13"},{"path":"/dev/ttyS14"},{"path":"/dev/ttyS15"},{"path":"/dev/ttyS16"},{"path":"/dev/ttyS17"},{"path":"/dev/ttyS18"},{"path":"/dev/ttyS19"},{"path":"/de
-- | -- | -- | -- | --

My CC26X2R1 ist connectet by TCP

**Comment by Koenkk** [comment]
This looks like an iobroker issue, please create an issue in their repo.
