### ISSUE TITLE
Herdsman crash - bringing down network until I reset the Zigbee network

### ISSUE THREAD

**Issue by BradleyFord** [Koenkk/zigbee-herdsman#740]
**Error:**
I recently upgraded to the latest version of the Coordinator firmware "20230507". After the update everything went perfectly ok.

But in the days since my network has randomly crashed, Mercenaruss from Zigstar logged in and confirmed that the Zigstar coordinator was working ok, and pressing the Zigbee reset button seemed to bring the network back online.
It has crashed twice again since then, but what is interesting when I was monitoring the latest crash it seemed that the Zigstar coordinator was still working ok, but Z2M showed everything as offline.

When I look at the timing when everything started to go offline I can see an error message that directly mentions Herdsman, hence I am wondering if the new version fo the coordinator firmware might be exposing a weakness in the code.

```
error 2023-08-08 05:41:56: Error: CommandResponse 0xa4c138dbfa0ecf7c/11 genOta.queryNextImageResponse({"status":152}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)
debug 2023-08-08 05:41:56: Error: CommandResponse 0xa4c138dbfa0ecf7c/11 genOta.queryNextImageResponse({"status":152}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```

**Logs:**
Attached is my Z2m logs
- The key error message is at row 34800 to 34802
- Then the devices start going offline from 34885 ("L1_Laundry2")

Logs Note:
- It is a new house, so some devices are in the Zigbee network but still offline. Hence the messages before the actual error, gradually we are bring the house online
- I have contacted Gledopto about trying to reduce the number of OTA requests that are coming from their lights... I have over 90 of them that seem to requestan OTA every 60 seconds.

[z2m log.txt](https://github.com/Koenkk/zigbee-herdsman/files/12292480/z2m.log.txt)

**Comment by Koenkk** [comment]
Please try the 20230716 firmware from [this thread](https://github.com/Koenkk/Z-Stack-firmware/issues/439) and report back there.
