### ISSUE TITLE
port doesn't accept symlink anymore

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee-herdsman#75]
since 0.10.0 we can't use a symlink anymore.
This is a regression, a lot of us do use udev rules to maintain a consistent name for our serial ports.
I've looked at https://github.com/serialport/node-serialport/issues/1476 and at several links from this issue;
I guess instead of counting on serialport to be able to list symlinks, it should be reasonable to see if the provided port is a symlink, follow it, and then search for the real device in SerialPort.list()

**Comment by lolorc** [comment]
I used to run two instances of z2m with 2 coordinators on the same computer, autodetection won't help in that case

**Comment by Koenkk** [comment]
Can you add on https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/adapter.ts#L46

```ts
serialPortOptions.path = fs.realpathSync(serialPortOptions.path);
```

and add to https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/adapter.ts#L6

```ts
import fs from 'fs';
```

**Comment by lolorc** [comment]
@Koenkk yep that's ok.
I've been to lazy, I've edited the js inside node_modules :)
```
Oct 17 10:25:42 winston:file logged 514 debug 2019-10-17T08:25:42: Using zigbee-herdsman with settings: '{"network":{"panID":"HIDDEN","extenedPanID":"HIDDEN","channelList":[],"networkKey":"HIDDEN"},"databasePath":"/home/pi/zigbee2mqtt.data/database.db","backupPath":"/home/pi/zigbee2mqtt.data/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/ttyUSB.CC2652"}}'
Oct 17 10:25:42 
Oct 17 10:25:43   zigbee-herdsman:adapter Path '/dev/ttyACM0' is valid for 'ZStackAdapter' +0ms

**Comment by Koenkk** [comment]
fixed, thanks!
