### ISSUE TITLE
zigbee-herdsman:zStack:unpi:parser throwing binary debug messages

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee-herdsman#76]
Looks like it logs unformatted binary data:
https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/z-stack/unpi/parser.ts#L45

**Comment by Koenkk** [comment]
At the point this data is still binary, what's wrong with it?

**Comment by lolorc** [comment]
having binary data in a log is useless as most of it is unprintable; and my terminal keeps beeping (visual beep here) all the time.
(yep I'm running with DEBUG=* all the time)
but it's definitely not a major issue but it's annoying. I've quickly tried a toJSON(), I failed :) I'm not even sure what kind of object frame is.

**Comment by Koenkk** [comment]
Running with DEBUG=zigbee-herdsman:controller* probably makes more sense.
