### ISSUE TITLE
how to add a new cluster to zigbee2mqtt locally

### ISSUE THREAD

**Issue by Anzal3c3** [Koenkk/zigbee-herdsman#807]
hello , i am looking to add a new cluster to zigbee2mqtt and possibly create a converter for a custom device. the device is an ir blaster can anyone possibly explain the steps in creating one and adding device. i am not a pro in javascript so any help would be appreciated.

Thanks in advance.

**Comment by xsp1989** [comment]
You can refer to my recent commit, I also happened to support a new infrared remote control
