### ISSUE TITLE
Issue with serialport v12 and node > v20.2.0

### ISSUE THREAD

**Issue by Nerivec** [Koenkk/zigbee-herdsman#870]
Came across these in some searches:
https://github.com/serialport/node-serialport/issues/2735
https://github.com/zwave-js/node-red-contrib-zwave-js/issues/288

"Error Resource temporarily unavailable Cannot lock port" is the reported error.

Installation scripts should ensure node v18 or v20.2.0 max (according to above links) is installed and used by Z2M until the issue is resolved.

**Comment by Koenkk** [comment]
Good to know! Until now I haven't seen reports of this with Z2M (both HA addon and Docker image still use 18)
