### ISSUE TITLE
Get strange error in latest z2m with the latest zigbee-herdsman

### ISSUE THREAD

**Issue by wastez** [Koenkk/zigbee-herdsman#893]

**Comment by wastez** [comment]
![image](https://github.com/Koenkk/zigbee-herdsman/assets/2268597/345982d2-055e-4606-8174-697998af2d8d)

**Comment by wastez** [comment]
Any ideas?
But I guess you need more? Or does this something mean to you?

**Comment by wastez** [comment]
Or is this related to zigbee herdsman converters?

**Comment by Nerivec** [comment]
It is converters. Seems you have a device that supports a value the converters don't know about. What's the device and what's the property you are trying to change when you get this error?

**Comment by wastez** [comment]
Can be closed. 
It was away in the next converter version.

**Comment by wastez** [comment]
I had a look in the code and as far I can say (I’m no coder) I think it was related to the Tuya changes.
