### ISSUE TITLE
ping fail

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee-herdsman#91]
i test the new lib.... and have a little bug
![grafik](https://user-images.githubusercontent.com/6681528/68892686-d2328f00-0723-11ea-9264-6c927dd76c03.png)
this is a hue bulb..but same problem i have with osram plugs

![grafik](https://user-images.githubusercontent.com/6681528/68892805-0a39d200-0724-11ea-94d6-c6bf9767f694.png)

the devs works fine .. only the ping error is strange

**Comment by Koenkk** [comment]
Could you sniff the traffic while this happens to see if the device really doesn't respond or if this is a zigbee-herdsman issue?

**Comment by arteck** [comment]
the device is anline and works (on/off).. only the ping is here wrong .. i think its a zigbee-herdsman issue

**Comment by Koenkk** [comment]
Ok, then I still need the sniff to find out what is going on (I don't have this device myself).

**Comment by arteck** [comment]
router device is here the problem
