### ISSUE TITLE
Commands before Startup

### ISSUE THREAD

**Issue by hobbyquaker** [Koenkk/zigbee-herdsman#95]
Hi Koen,

could you take a look at this issue and tell me your opinion about it? https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/74

Do you think that's something I should catch in node-red-contrib-zigbee or is this something that should be addressed in the herdsman? 

Regards,
Sebastian

**Comment by Koenkk** [comment]
You shouldnt submit commands to herdsman before it started, in herdsman we can add a check which throws an exception when this is done.

**Comment by hobbyquaker** [comment]
Thanks! Fixed that in node-red-contrib-zigbee.
