### ISSUE TITLE
Setting transmit power and receive gain

### ISSUE THREAD

**Issue by skandragon** [Koenkk/zigbee-herdsman#97]
I see in the docs there is a way to adjust the power level for transmit, and the RX gain for receive.

I am getting incredibly poor LQI as reported by a Xbee mapping my network -- all routers connected to my coordinator return poor LQI values, regardless of the TI device used -- I've tried PCB and modified external antenna versions of the USB stick, as well as a CC2530 (EBYTE E18-M31-IPX and -PCB).  All antennas were tested to be tuned to the correct frequency range, as sometimes ebay lies...

I am not sure how to convince the adapter to be given the `MT_MAC_SET_RX_GAIN_REQ` command or `SYS_STACK_TUNE` which appears to be the way to set the transmit power.

I'd love a mqtt message (as well as config option) to set this, so one could experiment on the fly.

Any guidance?  I've attempted to compare the javascript code to what bytes I would expect to be sent, but to little avail...

**Comment by Koenkk** [comment]
There are already quite some upvotes on https://github.com/Koenkk/zigbee2mqtt/issues/2253 so I will try to start working on it soon.
